Reporter 64
SukachevAlex/html-reporter pull request #107
Opened 2018-12-22 16:17 UTC by NexisSis

2018-12-22 16:34 UTC, hyrdbyrd reviewed
Фиксы! НУЖНЫ ФИКСЫ!

2018-12-22 16:34 UTC, ilya777grin23 commented on lib/static/components/controls/button.tsx
> +    isRed?: boolean;
Почему бы не использовать isDisabled?

2018-12-22 16:34 UTC, ilya777grin23 commented on lib/static/components/controls/button.tsx
> +        const {label, inverted, handler, basic, className, icon , isRed = false, isDisabled = false} = this.props;
Вот почему бы как раз не сделать isDisabled?

2018-12-22 16:34 UTC, ilya777grin23 commented on lib/static/components/controls/button.tsx
> +        const redBorderStyle = isRed ? { border: '1px solid deeppink' } : {};
Вот жешь!
const borderStyle = isDisabled ? {border: '1ps solid #fc0'} : {};

2018-12-22 16:34 UTC, ilya777grin23 commented on lib/static/components/controls/button.tsx
> +        const redBorderStyle = isRed ? { border: '1px solid deeppink' } : {};
И да, эта кнопка сместиться, если там box-sizing: content

2018-12-22 16:34 UTC, ilya777grin23 commented on lib/static/components/section/body/index.tsx
> +    onTestAccept = (stateName: string) => {
Зачем приравнивать к функции? Это же метод

2018-12-22 16:34 UTC, ilya777grin23 commented on lib/static/components/section/body/index.tsx
> +        this.props.actions.notAcceptTest(suite);
странное название для действия
Логичнее changeAcceptableState

2018-12-22 16:34 UTC, ilya777grin23 commented on lib/static/components/section/body/index.tsx
> +                }
```ts
const {suite = {}} = this.props;
let {canBeAccepted = undefined} = suite;

if (canBeAccepted === undefined) {
   canBeAccepted = !isAcceptDisabled;
}
```

2018-12-22 16:34 UTC, ilya777grin23 commented on lib/static/modules/reducer.ts
> +
?

2018-12-22 16:34 UTC, ilya777grin23 commented on lib/static/modules/reducer.ts
> +                    test.canBeAccepted = !test.canBeAccepted;
const test = findNode(suites, suitePath);
const {canBeAccepted} = test;
// Это конечно странно, но оно так и есть
// test.canBeAccepted = canBeAccepted === undefined ? false : true;
test.canBeAccepted = canBeAccepted !== undefined;

2018-12-22 16:34 UTC, ilya777grin23 commented on lib/static/modules/reducer.ts
> +        if (!test || (!test.canBeAccepted !== undefined && !test.canBeAccepted) ) {
!test.canBeAccepted уже даст true || false!!!
Оно не может быть undefined!!!

2018-12-22 16:34 UTC, ilya777grin23 commented on package.json
> +    "@types/react": "16.4.2",
Чего? Верни!

2018-12-22 17:25 UTC, SukachevAlex commented on lib/static/components/controls/button.tsx
> +    isRed?: boolean;
лучше не привязываться к цветам, все правильно. Завтра цвет поменяется, и придется лезть в код.

2018-12-22 19:12 UTC, hyrdbyrd requested changes

2018-12-22 19:12 UTC, ilya777grin23 commented on lib/static/components/section/body/index.tsx
> +        canBeAccepted?: boolean;
Вот тут и первая бага висит - если в сьюте будет canBeAccepted: false, то все браузеры не смогу быть заацепченны.

2018-12-22 19:12 UTC, ilya777grin23 commented on typings/suite-adapter.ts
> +    canBeAccepted?: boolean;
БАГА! БАГА!

2018-12-22 19:12 UTC, ilya777grin23 commented on lib/static/modules/reducer.ts
> +                    test.canBeAccepted = !test.canBeAccepted;
Тут зависла вторая бага. После запуска тестов, не отрисовываются новые состояния - статусы не ставятся, ретраи не добавляются, картинки не добавляются

2018-12-23 07:38 UTC, NexisSis commented on lib/static/components/controls/button.tsx
> +    isRed?: boolean;
потому что когда она отключена, не значит, что она красная

2018-12-23 07:41 UTC, NexisSis commented on lib/static/components/controls/button.tsx
> +        const redBorderStyle = isRed ? { border: '1px solid deeppink' } : {};
Изменил название, передвигается на 1 пиксель, вроде не заметно, если критично, можно что-то придумать.

2018-12-23 07:47 UTC, NexisSis commented on lib/static/components/section/body/index.tsx
> +        this.props.actions.notAcceptTest(suite);
Делал на основе предыдущего, если критично могу изменить

2018-12-23 07:47 UTC, NexisSis commented on lib/static/components/section/body/index.tsx
> +        this.props.actions.notAcceptTest(suite);
Предыдущий был  onTestAccept

2018-12-23 07:55 UTC, NexisSis commented on lib/static/modules/reducer.ts
> +
баг какой-то нету этого у меня

2018-12-23 07:55 UTC, NexisSis commented on lib/static/modules/reducer.ts
> +                    test.canBeAccepted = !test.canBeAccepted;
Да, я понял уже почему

2018-12-23 07:55 UTC, NexisSis commented on package.json
> +    "@types/react": "16.4.2",
Бага какая-то была с этой версией, ща попробую восстановить

2018-12-23 07:55 UTC, NexisSis commented on typings/suite-adapter.ts
> +    canBeAccepted?: boolean;
?

2018-12-23 07:55 UTC, NexisSis commented on lib/static/components/controls/button.tsx
> +        const {label, inverted, handler, basic, className, icon , isRed = false, isDisabled = false} = this.props;
выше ответил

2018-12-23 07:56 UTC, NexisSis commented on lib/static/components/section/body/index.tsx
> +    onTestAccept = (stateName: string) => {
Чуваки так выше сделали, я подумал, что нужно в таком формате продолжать :)

2018-12-23 07:57 UTC, NexisSis commented on lib/static/modules/reducer.ts
> +        if (!test || (!test.canBeAccepted !== undefined && !test.canBeAccepted) ) {
!undefind = true типо, да?

2018-12-23 08:12 UTC, hyrdbyrd approved these changes

2018-12-23 08:12 UTC, ilya777grin23 commented on lib/static/components/controls/button.tsx
> +    isBorderColor?: boolean;
isChecked?

2018-12-23 08:12 UTC, ilya777grin23 commented on lib/static/components/controls/button.tsx
> +    isBorderColor?: boolean;
Блин, ну это все еще не то(
Типа, это что-то типа чекбокса
Мне кажется логичным назвать это isChecked

2018-12-23 08:15 UTC, hyrdbyrd requested changes

2018-12-23 08:15 UTC, ilya777grin23 commented on lib/static/components/controls/button.tsx
> +    isBorderColor?: boolean;
isChecked по моему логичнее

2018-12-23 08:25 UTC, NexisSis commented on lib/static/modules/reducer.ts
> +        if (!test || (!test.canBeAccepted !== undefined && !test.canBeAccepted) ) {
Исправлено

2018-12-23 08:25 UTC, NexisSis commented on package.json
> +    "@types/react": "16.4.2",
Исправлено

2018-12-23 08:26 UTC, NexisSis commented on lib/static/components/controls/button.tsx
> +    isBorderColor?: boolean;
Согласен, ща сделаем

2018-12-24 09:40 UTC, hyrdbyrd requested changes
Нужна доработка

2018-12-24 09:40 UTC, ilya777grin23 commented on test/lib/static/components/section/state.jsx
> +describe('<State/>', function () {
Как сюда попал этот файл?

2018-12-24 09:40 UTC, ilya777grin23 commented on test/lib/static/components/utils.jsx
> +var default_state_1 = require("../../../../lib/static/modules/default-state");
И этот файл не нужен. Нам не нужно собирать тесты.

2018-12-24 09:40 UTC, ilya777grin23 commented on typings/suite-adapter.ts
> +    canBeAccepted?: boolean;
Это я к тому, что ты только для целого теста не ацептишь, а не для конкретного браузера. Это поведение не очевидно, и требует внимания. Думаю, стоит сделать многоуровневый неацепт (я знаю что это сложно, но если ты готов, а дедлайна нет, по попробуешь, ок?)

2019-02-03 08:25 UTC, closed without merging